service: analytics-tracker
useDotenv: true
build:
  esbuild: false
package:
  individually: false
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  currentStage: ${opt:stage, self:provider.stage}
  serverless-offline:
    resourceRoutes: true
    useSeparateProcesses: true
    httpPort: 4000
    host: 0.0.0.0
    noPrependStageInUrl: true
provider:
  name: aws
  runtime: nodejs22.x
  stage: ${file(./src/js-helpers/set-stage.js):setStage}
  httpApi:
    shouldStartNameWithService: true
functions: ${file(./src/js-helpers/load-services.js):functions}
resources:
  Resources:
    PaypalServiceProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi # our default Rest API logical ID
            - RootResourceId
        PathPart: '{proxy+}' # the endpoint in your API that is set as proxy
        RestApiId:
          Ref: ApiGatewayRestApi
